line-length = 120
target-version = "py314"
output-format = "full"

exclude = [
    ".git",
    ".venv",
]

[lint]
select = [
    "E",
    "W",    # pycodestyle,
    "C",    # to check McCabe complexity.
    "F",    # Pyflakes
    "UP",   # pyupgrade
    "B",    # flake8-bugbear
    "C4",   # flake8-comprehensions (C4)
    "I",    # isort
    "PT",   # flake8-pytest-style
    "N",    # pep8-naming
    "PERF", # Perflint
    "PL",   # Pylint
    "ERA",  # eradicate
    "T20",  # flake8-print
    "RET",  # flake8-return
    "A",    # flake8-builtins
    "C90",  # mccabe
    "ISC",  # flake8-implicit-str-concat
    "FLY",  # flynt (join -> f-string)
    "G",    # flake8-logging-format
    "LOG",  # flake8-logging
    "PGH",  # pygrep-hooks
    "PIE",  # flake8-pie
    "Q",    # flake8-quotes
    "RSE",  # flake8-raise
    "RUF",  # Ruff-specific rules
    "S",    # flake8-bandit
    "SIM",  # flake8-simplify
    "T10",  # flake8-debugger
    "DTZ",  # flake8-datetimez
    "ANN",  # flake8-annotations
    "TRY",  # flake8-try-except
    "PTH",  # pathlib
]

ignore = ["TRY400", "T201", "TRY003", "ANN401"]

[format]
quote-style = "single"

[lint.pylint]
max-args = 15
max-bool-expr = 5
max-nested-blocks = 5
max-public-methods = 13
max-returns = 6
max-statements = 50

[lint.flake8-quotes]
inline-quotes = "single"

[lint.mccabe]
max-complexity = 10
